# Configuration File for sense_logger tools

# Sense Account Credentials (use sense-login to update)
[Sense]
# Account Credentials (use sense-login to update)
credential-file = "~/.sense.json"

# Cooked Threshold, even when the Solar inverters are off my Sense unit reads a
# small amount of current.  Data points less than this value will be clamped to 0.
# Specify a value in Watts, it will be adjusted to the appropriate time scale.
production_threshold = 3.0

# MQTT Broker configuration (only used for RealTime publishing)
[MQTT]
broker = "tcp://example.net:1883"
username = ""
password = ""
topic = "sense/realtime"

# InfluxDB Connection
[InfluxDB.Server]
url = "http://example.net:8086"
org = "my-org"
token = "token"

# Bucket and Measurements
[InfluxDB.Hour]
# One hour of per minute data
bucket = "EnergyPerMinute"
measurement = "sense_trend"

[InfluxDB.Day]
# One day of per hour data
bucket = "Energy"
measurement = "hour_sense_trend"

[InfluxDB.Month]
# One month of per day data
bucket = "Energy"
measurement = "day_sense_trend"

[InfluxDB.Year]
# One year of per month data
bucket = "Energy"
measurement = "month_sense_trend"

[InfluxDB.RealTime]
# High frequency "real time" streaming data
bucket = "EnergyRealtime"
measurement = "sense_realtime"
